import "./globals.css";

export const metadata = {
	title: process.env.TITLE ?? "Priorderity app",
	description: "Generated by create next app",
};

export default function RootLayout ( {
	children,
}: {
	children: React.ReactNode;
} ) {
	return (
		<html lang="en">
			<body>
				<main className="flex min-h-screen flex-col items-center bg-background">
					{children}
				</main>
			</body>
		</html>
	);
}
